language: node_js
node_js:
  - "13"
notifications:
  recipients:
    - piro.outsider.reflex@gmail.com
before_script:
  - cd webextensions
  - npm install
  - make update_extlib
  - make install_extlib
script:
  - make lint
before_deploy:
  - make
deploy:
  provider: releases
  api_key:
    secure: "hr00ssQU0P4AHVkqrl1ZzkzhWe0zUTJIMD9R828Tu2qrA4syzCqsTvXkaELhMoR/xwQwJFl4E5OoUAziwkpOWE2kd8vQ1//ltv+TqrjjnZx+y+M8qw5CqcvYyPjqEAruyeibtTULk8L7ktTYvu6Q3LjKIVXCjZI43TmLTwzZ/9c="
  file:
    - treestyletab-we.xpi
  skip_cleanup: true
  on:
    repo: piroor/treestyletab
    tags: true
