name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        npm install
        make
    - uses: actions/upload-artifact@master
      with:
        name: treestyletab-we.xpi
        path: treestyletab-we.xpi
